#version 460 core

vec3 GetWeight(vec3 p,vec3 v0, vec3 v1, vec3 v2) {
	float a = 1 / length(p- v0);
	float b = 1 / length(p- v1);
	float c = 1 / length(p- v2);
	return normalize(vec3(a, b, c));
}

vec3 Lerp3(vec3 v0, vec3 v1, vec3 v2, float a, float b, float c) {


	return v0 * a + v1 * b + v2 * c;
}
struct Ray {
	vec3 origin;
	vec3 direction;
};
struct Material {
	vec4 col;
	float roughness;
	float metallic;
	float emissive;
	float refractiveIndex;
};
struct Sphere {
	vec3 position;
	float radius;
	vec4 color;
	Material material;
};
struct UV {
	float x, y;
};
struct BVHnode {
	float maxBound[3];
	float minBound[3];
	int index;
	int amount;
};

struct Object {
	vec3 position;
	uint startFace;
	vec3 rotation;
	uint facesAmount;
	vec3 scale;
	int materialIndex;
	vec2 padding;
	uint bvhIndex;
	uint priorityIndex;
};
struct HitInfo {
	vec3 position;
	vec3 normal;
	int objectIndex;
	float distance;
	Material material;
};


layout(std430, binding = 1) buffer colorBuffer {
	vec4 colorData[];
};
layout(std430, binding = 2) buffer vertexBuffer {
	vec4 vertexData[];
};
layout(std430, binding = 3) buffer normalBuffer {
	vec4 normalData[];
};
layout(std430, binding = 4) buffer uvBuffer {
	UV uvData[];
};
layout(std430, binding = 5) buffer faceBuffer {
	ivec4 faceData[];
};
layout(std430, binding = 6) buffer objectBuffer {
	Object objectData[];
};
layout(std430, binding = 7) buffer materialBuffer {
	Material materialData[];
};
layout(std430, binding = 8) buffer bvhBuffer {
	BVHnode bvhData[];
};
layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D screen;
uniform uint objectAmount;
uniform uint progress;
uint NextRandom(inout uint state)
{
	state = state * 747796405 + 2891336453;
	uint result = ((state >> ((state >> 28) + 4)) ^ state) * 277803737;
	result = (result >> 22) ^ result;
	return result;
}

float RandomValue(inout uint state)
{
	return NextRandom(state) / 4294967295.0; // 2^32 - 1
}
float RandomValueNormalDistribution(inout uint seed)
{
	float theta = 2 * 3.14159265359 * RandomValue(seed);
	float rho = sqrt(-2.0 * log(RandomValue(seed)));
	return rho * cos(theta);
}
vec3 GetRandomDirection(inout uint seed)
{
	float x = RandomValueNormalDistribution(seed);
	float y = RandomValueNormalDistribution(seed);
	float z = RandomValueNormalDistribution(seed);
	vec3 vec = normalize(vec3(x, y, z));
	return vec;
}

HitInfo GetHitInfoFromRay(Ray ray)
{
	HitInfo hitInfo;
	//hitInfo.normal = vec3(0, 0, 0);
	//hitInfo.position = vec3(0, 0, 0);
	hitInfo.objectIndex = -1;
	hitInfo.distance = 999999999;
	float kEpsilon = 0.0000001;

	for (uint objIndex=0; objIndex <objectAmount; objIndex++)
	{
		
		HitInfo tempHitInfo;
		//tempHitInfo=hitInfo;
		//tempHitInfo.normal = vec3(0, 0, 0);
		//tempHitInfo.position = vec3(0, 0, 0);
		tempHitInfo.distance=999999999;
		tempHitInfo.objectIndex = -1;
		for (uint i = objectData[objIndex].startFace*3; i< (objectData[objIndex].startFace+objectData[objIndex].facesAmount) * 3;i+=3)
		{
							
			vec3 v0 = vertexData[faceData[i].x].xyz+objectData[objIndex].position.xyz;
			vec3 v1 = vertexData[faceData[i+1].x].xyz+objectData[objIndex].position.xyz;
			vec3 v2 = vertexData[faceData[i+2].x].xyz+objectData[objIndex].position.xyz;
			vec3 v0v1 = v1 - v0;
			vec3 v0v2 = v2 - v0;
			vec3 N = cross(v0v1, v0v2);
			float NdotRayDirection = dot(N, ray.direction);
			if (abs(NdotRayDirection) < kEpsilon) // Almost 0
			{
				continue;
			}
			float d = -dot(N, v0);
			float t = -(dot(N, ray.origin) + d) / NdotRayDirection;
		
			if (t < 0) continue; // The triangle is behind
			// Compute the intersection point using equation 1
			vec3 P = ray.origin + t * ray.direction;
			vec3 Ne;// Vector perpendicular to triangle's plane
			 // Test sidedness of edge v0v1
			vec3 v0p = P - v0;
			Ne = cross(v0v1, v0p);
			if (dot(N, Ne) < 0) continue;
			// Test sidedness of edge v2v1
			vec3 v2v1 = v2 - v1;
			vec3 v1p = P - v1;
			Ne = cross(v2v1, v1p);
			if (dot(N, Ne) < 0) continue; // P is on the right side

			// Test sidedness of P w.r.t. edge v2v0
			vec3 v2v0 = v0 - v2;
			vec3 v2p = P - v2;
			Ne = cross(v2v0, v2p);
			if (dot(N, Ne) < 0) continue; // P is on the right side
			if (t > tempHitInfo.distance) continue;
			tempHitInfo.distance = t;
			vec3 actualNormalv0 = normalData[faceData[i].z].xyz;
			vec3 actualNormalv1 = normalData[faceData[i + 1].z].xyz;
			vec3 actualNormalv2 = normalData[faceData[i + 2].z].xyz;
			vec3 weight = GetWeight(P, v0, v1, v2);
			vec3 actualNormal = normalize(Lerp3(actualNormalv0, actualNormalv1, actualNormalv2, weight.x, weight.y, weight.z));
			tempHitInfo.position=P;
			tempHitInfo.normal=actualNormal;
			tempHitInfo.objectIndex = objectData[objIndex].materialIndex;
			//tempHitInfo.objectIndex = int(objIndex);

		}
		
		if (tempHitInfo.distance>hitInfo.distance) continue;
		hitInfo=tempHitInfo;
	}
	return hitInfo;
}


uniform float halffov; 
void main()
{
	vec4 pixel = vec4(0.5, 0.5, 0.5, 1.0);
	//vec4 pixel = vec4(0.0, 0.5, 0.0, 1.0);
	ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
	ivec2 dimensions = imageSize(screen);
	float y = float(pixelCoords.y * 2 - float(dimensions.y)) / float(dimensions.y);
	float x = float(pixelCoords.x * 2 - float(dimensions.x)) / float(dimensions.y);

	vec3 cameraPos = vec3(0, 0, -3.5f);
	vec3 rayOrigin = cameraPos + vec3(x, y, atan(halffov * 3.14 / 180));
	vec3 rayDir = normalize(rayOrigin - cameraPos);

	vec3 debug;
	vec3 col = vec3(1, 1, 1);
	vec3 light = vec3(0, 0, 0);
	uint repetition = 1;
	float distance;
	for (int i = 0; i < repetition; i++) 
	{
		vec3 tempCol = vec3(1, 1, 1);
		vec3 tempLight = vec3(0, 0, 0);
		uint rng = pixelCoords.x + pixelCoords.y * dimensions.x + dimensions.x * dimensions.y * i* progress;
		vec3 randomDir= GetRandomDirection(rng);
		rayOrigin = cameraPos + vec3(x, y, 1/tan(halffov * 3.14 / 180));
		rayDir = normalize(rayOrigin - cameraPos+randomDir*0.0001);
		for (int j = 0; j <1; j++)
		{
			Ray ray;
			ray.origin = rayOrigin;
			ray.direction = rayDir;
			HitInfo hitInfo = GetHitInfoFromRay(ray);
			if (hitInfo.objectIndex == -1)
			{
				//hitInfo.position = vec3(0, 0, 0);
				//hitInfo.normal = vec3(0, 0, 0);
				break;
			}
			rng = pixelCoords.x + pixelCoords.y * dimensions.x + dimensions.x * dimensions.y * (i+j+progress);
			randomDir= GetRandomDirection(rng);
			
			rayDir = normalize(mix(reflect(rayDir,hitInfo.normal),normalize(hitInfo.normal*1+randomDir*1 ),materialData[hitInfo.objectIndex].roughness));
			//rayDir=normalize(reflect(rayDir,hitInfo.normal)+randomDir*materialData[hitInfo.objectIndex].roughness);
			rayOrigin = hitInfo.position + rayDir*0.00001;
			tempLight += materialData[hitInfo.objectIndex].emissive * tempCol;
			debug=hitInfo.normal;
			tempCol *= materialData[hitInfo.objectIndex].col.xyz;
			float p = max(tempCol.x, max(tempCol.y, tempCol.z));
			if (RandomValue(rng) >= p) {
				break;
			}
			tempCol *= 1.0 / p; 
		}
		light += tempLight / repetition;
		light = debug;
	}
	pixel = vec4(light,1.0);
	vec4 previousCol=colorData[pixelCoords.x + pixelCoords.y * dimensions.x];
	vec4 outColor = previousCol * progress / (progress + 1) + pixel / (progress + 1);
	colorData[pixelCoords.x + pixelCoords.y * dimensions.x] = outColor;
	if (progress == 100) {
		//colorData[pixelCoords.x + pixelCoords.y * dimensions.x] = pixel;
	}
	vec4 blurColor = vec4(0, 0, 0, 0);
	int blurAmount = 0;
	for (int i = -blurAmount; i <= blurAmount; i++) {
		for (int j = -blurAmount; j <= blurAmount; j++) {
			blurColor += colorData[max(0, pixelCoords.x + i) + max(0, pixelCoords.y + j) * dimensions.x];
		}
	}
	uint blurPixels = ((blurAmount * 2 + 1) * (blurAmount * 2 + 1));
	blurColor.xyz = blurColor.xyz / (blurPixels*4)+outColor.xyz*3/4;
	//pixel = vec4(float(pixelCoords.x)/ float(dimensions.x), float(pixelCoords.y)/ float(dimensions.y), 0, 1);
	//uint rng=pixelCoords.x+pixelCoords.y*dimensions.x;
	//pixel=vec4(GetRandomDirection(rng),1);
	imageStore(screen, pixelCoords, blurColor);

}